-- Trunfo do Sertão — schema inicial
create extension if not exists pgcrypto;

-- ===== teams =====
create table if not exists public.teams (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  name text not null,
  city text,
  state text,
  logo_url text,
  cover_url text,
  description text,
  instagram text,
  whatsapp text,
  website text,
  sponsors text[] not null default '{}',
  founded_year int,
  sertoes_participations int not null default 0,
  titles_general int not null default 0,
  titles_category int not null default 0,
  featured boolean not null default false,
  status text not null default 'active' check (status in ('active','hidden')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.team_secrets (
  team_id uuid primary key references public.teams(id) on delete cascade,
  edit_token text not null
);

-- ===== vehicles (as cartas) =====
create table if not exists public.vehicles (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams(id) on delete cascade,
  slug text unique not null,
  card_number int generated by default as identity unique,
  name text not null,
  brand text,
  model text,
  year int,
  race_number text,
  category_id text not null,
  type text not null check (type in ('carro','utv','moto','quadri','apoio')),
  photo_url text,
  pilot_name text,
  pilot_photo_url text,
  pilot_city text,
  navigator_name text,
  navigator_photo_url text,
  specs jsonb not null default '{}',
  history jsonb not null default '{}',
  description text,
  sponsors text[] not null default '{}',
  likes_count int not null default 0,
  featured boolean not null default false,
  status text not null default 'active' check (status in ('active','hidden')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists vehicles_team_id_idx on public.vehicles(team_id);
create index if not exists vehicles_category_id_idx on public.vehicles(category_id);
create index if not exists vehicles_likes_idx on public.vehicles(likes_count desc);
create index if not exists teams_slug_idx on public.teams(slug);
create index if not exists vehicles_slug_idx on public.vehicles(slug);

-- ===== likes =====
create table if not exists public.likes (
  id uuid primary key default gen_random_uuid(),
  vehicle_id uuid not null references public.vehicles(id) on delete cascade,
  fingerprint text not null,
  created_at timestamptz not null default now(),
  unique(vehicle_id, fingerprint)
);

create or replace function public.handle_like_insert() returns trigger
language plpgsql as $$
begin
  update public.vehicles set likes_count = likes_count + 1 where id = new.vehicle_id;
  return new;
end;
$$;

create or replace function public.handle_like_delete() returns trigger
language plpgsql as $$
begin
  update public.vehicles set likes_count = greatest(0, likes_count - 1) where id = old.vehicle_id;
  return old;
end;
$$;

drop trigger if exists on_like_insert on public.likes;
create trigger on_like_insert after insert on public.likes
  for each row execute function public.handle_like_insert();

drop trigger if exists on_like_delete on public.likes;
create trigger on_like_delete after delete on public.likes
  for each row execute function public.handle_like_delete();

-- ===== updated_at trigger =====
create or replace function public.set_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists teams_set_updated_at on public.teams;
create trigger teams_set_updated_at before update on public.teams
  for each row execute function public.set_updated_at();

drop trigger if exists vehicles_set_updated_at on public.vehicles;
create trigger vehicles_set_updated_at before update on public.vehicles
  for each row execute function public.set_updated_at();

-- ===== app_config (admin pin) =====
create table if not exists public.app_config (
  key text primary key,
  value text not null
);

-- ===== RLS =====
alter table public.teams enable row level security;
alter table public.team_secrets enable row level security;
alter table public.vehicles enable row level security;
alter table public.likes enable row level security;
alter table public.app_config enable row level security;

drop policy if exists "public reads active teams" on public.teams;
create policy "public reads active teams" on public.teams for select using (status = 'active');

drop policy if exists "public reads active vehicles" on public.vehicles;
create policy "public reads active vehicles" on public.vehicles for select using (status = 'active');

drop policy if exists "public reads likes" on public.likes;
create policy "public reads likes" on public.likes for select using (true);

-- team_secrets e app_config: nenhuma policy pra anon/authenticated (default deny). Só RPC (security definer) acessa.

-- ===== storage bucket =====
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('cards', 'cards', true, 5242880, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public = true, file_size_limit = 5242880, allowed_mime_types = array['image/jpeg','image/png','image/webp'];

drop policy if exists "anon upload cards" on storage.objects;
create policy "anon upload cards" on storage.objects for insert to anon, authenticated
  with check (bucket_id = 'cards');

drop policy if exists "public read cards" on storage.objects;
create policy "public read cards" on storage.objects for select using (bucket_id = 'cards');

-- ===== helper: slug generator com sufixo se duplicado =====
create or replace function public.next_free_slug(p_table text, p_base text) returns text
language plpgsql as $$
declare
  candidate text := p_base;
  i int := 1;
  exists_row boolean;
begin
  loop
    execute format('select exists(select 1 from public.%I where slug = $1)', p_table) into exists_row using candidate;
    exit when not exists_row;
    i := i + 1;
    candidate := p_base || '-' || i;
  end loop;
  return candidate;
end;
$$;

-- ===== token helpers =====
create or replace function public.gen_edit_token() returns text
language sql as $$
  select upper(substr(encode(gen_random_bytes(6), 'hex'), 1, 4)) || '-' || upper(substr(encode(gen_random_bytes(6), 'hex'), 5, 4));
$$;

create or replace function public.is_admin_pin(p_pin text) returns boolean
language plpgsql security definer set search_path = public as $$
declare
  h text;
begin
  select value into h from public.app_config where key = 'admin_pin_hash';
  if h is null or p_pin is null then return false; end if;
  return h = crypt(p_pin, h);
end;
$$;

create or replace function public.is_valid_team_token(p_team_id uuid, p_token text) returns boolean
language plpgsql security definer set search_path = public as $$
declare
  real_token text;
begin
  if p_token is null then return false; end if;
  if public.is_admin_pin(p_token) then return true; end if;
  select edit_token into real_token from public.team_secrets where team_id = p_team_id;
  return real_token is not null and real_token = p_token;
end;
$$;

-- ===== RPCs públicas =====
create or replace function public.create_team(p jsonb) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_id uuid;
  v_slug text;
  v_token text;
begin
  v_slug := public.next_free_slug('teams', p->>'slug');
  v_token := public.gen_edit_token();
  insert into public.teams (slug, name, city, state, description, instagram, whatsapp, website, founded_year)
  values (v_slug, p->>'name', p->>'city', p->>'state', p->>'description', p->>'instagram', p->>'whatsapp', p->>'website',
          nullif(p->>'founded_year','')::int)
  returning id into v_id;
  insert into public.team_secrets (team_id, edit_token) values (v_id, v_token);
  return jsonb_build_object('id', v_id, 'slug', v_slug, 'edit_token', v_token);
end;
$$;

create or replace function public.verify_team_token(p_team_id uuid, p_token text) returns boolean
language sql security definer set search_path = public as $$
  select public.is_valid_team_token(p_team_id, p_token);
$$;

create or replace function public.update_team(p_team_id uuid, p_token text, p jsonb) returns void
language plpgsql security definer set search_path = public as $$
begin
  if not public.is_valid_team_token(p_team_id, p_token) then
    raise exception 'invalid token';
  end if;
  update public.teams set
    name = coalesce(p->>'name', name),
    city = coalesce(p->>'city', city),
    state = coalesce(p->>'state', state),
    logo_url = coalesce(p->>'logo_url', logo_url),
    cover_url = coalesce(p->>'cover_url', cover_url),
    description = coalesce(p->>'description', description),
    instagram = coalesce(p->>'instagram', instagram),
    whatsapp = coalesce(p->>'whatsapp', whatsapp),
    website = coalesce(p->>'website', website),
    sponsors = coalesce((select array_agg(x) from jsonb_array_elements_text(p->'sponsors') x), sponsors),
    founded_year = coalesce(nullif(p->>'founded_year','')::int, founded_year)
  where id = p_team_id;
end;
$$;

create or replace function public.create_vehicle(p_team_id uuid, p_token text, p jsonb) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_id uuid;
  v_slug text;
begin
  if not public.is_valid_team_token(p_team_id, p_token) then
    raise exception 'invalid token';
  end if;
  v_slug := public.next_free_slug('vehicles', p->>'slug');
  insert into public.vehicles (team_id, slug, name, brand, model, year, race_number, category_id, type,
                                photo_url, pilot_name, pilot_photo_url, pilot_city, navigator_name, navigator_photo_url,
                                specs, history, description, sponsors)
  values (p_team_id, v_slug, p->>'name', p->>'brand', p->>'model', nullif(p->>'year','')::int, p->>'race_number',
          p->>'category_id', p->>'type', p->>'photo_url', p->>'pilot_name', p->>'pilot_photo_url', p->>'pilot_city',
          p->>'navigator_name', p->>'navigator_photo_url',
          coalesce(p->'specs', '{}'::jsonb), coalesce(p->'history', '{}'::jsonb), p->>'description',
          coalesce((select array_agg(x) from jsonb_array_elements_text(p->'sponsors') x), '{}'))
  returning id into v_id;
  return jsonb_build_object('id', v_id, 'slug', v_slug);
end;
$$;

create or replace function public.update_vehicle(p_vehicle_id uuid, p_token text, p jsonb) returns void
language plpgsql security definer set search_path = public as $$
declare
  v_team_id uuid;
begin
  select team_id into v_team_id from public.vehicles where id = p_vehicle_id;
  if v_team_id is null or not public.is_valid_team_token(v_team_id, p_token) then
    raise exception 'invalid token';
  end if;
  update public.vehicles set
    name = coalesce(p->>'name', name),
    brand = coalesce(p->>'brand', brand),
    model = coalesce(p->>'model', model),
    year = coalesce(nullif(p->>'year','')::int, year),
    race_number = coalesce(p->>'race_number', race_number),
    category_id = coalesce(p->>'category_id', category_id),
    type = coalesce(p->>'type', type),
    photo_url = coalesce(p->>'photo_url', photo_url),
    pilot_name = coalesce(p->>'pilot_name', pilot_name),
    pilot_photo_url = coalesce(p->>'pilot_photo_url', pilot_photo_url),
    pilot_city = coalesce(p->>'pilot_city', pilot_city),
    navigator_name = coalesce(p->>'navigator_name', navigator_name),
    navigator_photo_url = coalesce(p->>'navigator_photo_url', navigator_photo_url),
    specs = coalesce(p->'specs', specs),
    history = coalesce(p->'history', history),
    description = coalesce(p->>'description', description),
    sponsors = coalesce((select array_agg(x) from jsonb_array_elements_text(p->'sponsors') x), sponsors)
  where id = p_vehicle_id;
end;
$$;

create or replace function public.delete_vehicle(p_vehicle_id uuid, p_token text) returns void
language plpgsql security definer set search_path = public as $$
declare
  v_team_id uuid;
begin
  select team_id into v_team_id from public.vehicles where id = p_vehicle_id;
  if v_team_id is null or not public.is_valid_team_token(v_team_id, p_token) then
    raise exception 'invalid token';
  end if;
  delete from public.vehicles where id = p_vehicle_id;
end;
$$;

create or replace function public.toggle_like(p_vehicle_id uuid, p_fingerprint text) returns int
language plpgsql security definer set search_path = public as $$
declare
  v_liked boolean;
  v_count int;
begin
  select exists(select 1 from public.likes where vehicle_id = p_vehicle_id and fingerprint = p_fingerprint) into v_liked;
  if v_liked then
    delete from public.likes where vehicle_id = p_vehicle_id and fingerprint = p_fingerprint;
  else
    insert into public.likes (vehicle_id, fingerprint) values (p_vehicle_id, p_fingerprint)
    on conflict do nothing;
  end if;
  select likes_count into v_count from public.vehicles where id = p_vehicle_id;
  return v_count;
end;
$$;

create or replace function public.admin_verify(p_pin text) returns boolean
language sql security definer set search_path = public as $$
  select public.is_admin_pin(p_pin);
$$;

create or replace function public.admin_get_team_token(p_pin text, p_team_id uuid) returns text
language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin_pin(p_pin) then raise exception 'invalid pin'; end if;
  return (select edit_token from public.team_secrets where team_id = p_team_id);
end;
$$;

create or replace function public.admin_set_status(p_pin text, p_kind text, p_id uuid, p_status text) returns void
language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin_pin(p_pin) then raise exception 'invalid pin'; end if;
  if p_kind = 'team' then
    update public.teams set status = p_status where id = p_id;
  elsif p_kind = 'vehicle' then
    update public.vehicles set status = p_status where id = p_id;
  else
    raise exception 'invalid kind';
  end if;
end;
$$;

create or replace function public.admin_set_featured(p_pin text, p_kind text, p_id uuid, p_featured boolean) returns void
language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin_pin(p_pin) then raise exception 'invalid pin'; end if;
  if p_kind = 'team' then
    update public.teams set featured = p_featured where id = p_id;
  elsif p_kind = 'vehicle' then
    update public.vehicles set featured = p_featured where id = p_id;
  else
    raise exception 'invalid kind';
  end if;
end;
$$;

-- ===== permissões =====
revoke all on function public.create_team(jsonb) from public;
revoke all on function public.verify_team_token(uuid, text) from public;
revoke all on function public.update_team(uuid, text, jsonb) from public;
revoke all on function public.create_vehicle(uuid, text, jsonb) from public;
revoke all on function public.update_vehicle(uuid, text, jsonb) from public;
revoke all on function public.delete_vehicle(uuid, text) from public;
revoke all on function public.toggle_like(uuid, text) from public;
revoke all on function public.admin_verify(text) from public;
revoke all on function public.admin_get_team_token(text, uuid) from public;
revoke all on function public.admin_set_status(text, text, uuid, text) from public;
revoke all on function public.admin_set_featured(text, text, uuid, boolean) from public;

grant execute on function public.create_team(jsonb) to anon, authenticated;
grant execute on function public.verify_team_token(uuid, text) to anon, authenticated;
grant execute on function public.update_team(uuid, text, jsonb) to anon, authenticated;
grant execute on function public.create_vehicle(uuid, text, jsonb) to anon, authenticated;
grant execute on function public.update_vehicle(uuid, text, jsonb) to anon, authenticated;
grant execute on function public.delete_vehicle(uuid, text) to anon, authenticated;
grant execute on function public.toggle_like(uuid, text) to anon, authenticated;
grant execute on function public.admin_verify(text) to anon, authenticated;
grant execute on function public.admin_get_team_token(text, uuid) to anon, authenticated;
grant execute on function public.admin_set_status(text, text, uuid, text) to anon, authenticated;
grant execute on function public.admin_set_featured(text, text, uuid, boolean) to anon, authenticated;
